# docker-compose.production.yml
version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:8000"
      - "443:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.production
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: reconciliation_prod
      POSTGRES_USER: reconciliation_user
      POSTGRES_PASSWORD: secure_production_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    restart: always

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: always

  celery:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A reconciliation_agent worker --loglevel=info
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    restart: always

  celery-beat:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A reconciliation_agent beat --loglevel=info
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres_data:
  redis_data:
